### PR TITLE
FINAL SETUP

### PR DESCRIPTION
**Pull request by AACHOURMOHAMED**
Greetings 👋🏻
Thanks for taking the time to review my code

Changes implemented
✅ Create rails react single application
✅ Create Greeting API endpoint (API/v1/greeting)
✅ Create a Greeting route using React
✅ Create a redux store, action, and a reducer to fetch the data from the API ('/greeting')

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
### Hello  @AACHOURMOHAMED                         :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job making your roude api/v1 t:+1: 

 ## Required Changes 
**NOTE:** _I am writing the required changes here because I am unable to add the comments on the parts of code because they weren't changed_
- [ ] Please add `babel.config.js` and  `webpack.config.js` as shown on this [tutorial](https://betterprogramming.pub/react-with-rails-2022-bd28e1fcd355#ad0a)[the totorial](https://betterprogramming.pub/react-with-rails-2022-bd28e1fcd355#ad0a) 
- [ ] On Gemfile line 19 the gem name should be `gem 'jsbundling-rails'`
- [ ] I am getting this error when running your app, it is comming from `index.json.jbuilder` file
image




 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AACHOURMOHAMED** [comment]
Thank you for the review
but it's working on my side 
Screenshot 2022-12-07 124506
 and I added all that you required
yarn install

**Comment by GzimAsani** [comment]
> Thank you for the review but it's working on my side Screenshot 2022-12-07 124506 and I added all what you required

For me it worked once I deleted that and it is a requirement that only the root be present as a html file on the rails side
image

**Comment by AACHOURMOHAMED** [comment]
> > Thank you for the review but it's working on my side Screenshot 2022-12-07 124506 and I added all what you required
> 
> For me it worked once I deleted that and it is a requirement that only the root be present as a html file on the rails side image

yes I did 
kindly take a look on the screen shot that I will provide you
Screenshot 2022-12-07 125122

Screenshot 2022-12-07 125458

**Review by m05e5 — APPROVED** [review]
Hi @AACHOURMOHAMED , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
goodjob

## Highlights
✔️ your linters are all ok
✔️ Descriptive PR 

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
